version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name app --s3-location s3://ope-imamura-cicdkadai/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src